# Generated by Django 4.1.1 on 2022-09-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('retailer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Retailer name', max_length=64, unique=True)),
                ('number_1', models.CharField(help_text='Phone number 1', max_length=10, unique=True)),
                ('number_2', models.CharField(blank=True, help_text='Phone number 2', max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('salesman_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Salesman name', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(help_text='Amount')),
                ('date', models.DateField(auto_now_add=True, help_text='Date')),
                ('retailer', models.ForeignKey(help_text='Retailer ID', on_delete=django.db.models.deletion.CASCADE, related_name='retailer_invoices', to='notifier.retailer')),
                ('salesman', models.ForeignKey(help_text='Salesman ID', on_delete=django.db.models.deletion.CASCADE, related_name='salesman_invoices', to='notifier.salesman')),
            ],
        ),
    ]
